"""Replaced answer and query tabels with message

Revision ID: 0725003b89aa
Revises: b89b4f59d675
Create Date: 2025-11-28 19:27:04.325191

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0725003b89aa"
down_revision: Union[str, None] = "b89b4f59d675"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("parent_message_id", sa.Integer(), nullable=True),
        sa.Column("model_used", sa.String(length=100), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["parent_message_id"],
            ["message.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_message_parent_message_id"),
        "message",
        ["parent_message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_message_session_id"), "message", ["session_id"], unique=False
    )
    op.create_index(op.f("ix_message_user_id"), "message", ["user_id"], unique=False)
    # update references on dependent tables before dropping 'answer' and 'query'
    op.add_column("source", sa.Column("message_id", sa.Integer(), nullable=False))
    op.drop_index(op.f("ix_source_answer_id"), table_name="source")
    op.create_index(
        op.f("ix_source_message_id"), "source", ["message_id"], unique=False
    )
    op.drop_constraint(op.f("source_answer_id_fkey"), "source", type_="foreignkey")
    op.create_foreign_key(None, "source", "message", ["message_id"], ["id"])
    op.drop_column("source", "answer_id")

    op.add_column("token_usage", sa.Column("message_id", sa.Integer(), nullable=True))
    op.drop_index(op.f("ix_token_usage_query_id"), table_name="token_usage")
    op.create_index(
        op.f("ix_token_usage_message_id"), "token_usage", ["message_id"], unique=False
    )
    op.drop_constraint(
        op.f("token_usage_query_id_fkey"), "token_usage", type_="foreignkey"
    )
    op.create_foreign_key(None, "token_usage", "message", ["message_id"], ["id"])
    op.drop_column("token_usage", "query_id")

    # drop 'answer' first, then 'query' to avoid dependent object errors
    op.drop_index(op.f("ix_answer_query_id"), table_name="answer")
    op.drop_table("answer")

    op.drop_index(op.f("ix_query_parent_query_id"), table_name="query")
    op.drop_index(op.f("ix_query_session_id"), table_name="query")
    op.drop_index(op.f("ix_query_user_id"), table_name="query")
    op.drop_table("query")

    op.drop_index(
        op.f("ix_user_service_credential_api_key_id"),
        table_name="user_service_credential",
    )
    op.drop_index(
        op.f("ix_user_service_credential_service_id"),
        table_name="user_service_credential",
    )
    op.drop_index(
        op.f("ix_user_service_credential_user_id"), table_name="user_service_credential"
    )
    op.drop_index(
        op.f("ix_user_service_credential_user_settings_id"),
        table_name="user_service_credential",
    )
    op.drop_table("user_service_credential")

    op.drop_index(op.f("ix_user_api_keys_user_id"), table_name="user_api_keys")
    op.drop_index(op.f("ix_user_api_keys_user_settings_id"), table_name="user_api_keys")
    op.drop_table("user_api_keys")

    op.drop_index(op.f("ix_service_catalog_slug"), table_name="service_catalog")
    op.drop_table("service_catalog")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "token_usage",
        sa.Column("query_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "token_usage", type_="foreignkey")
    op.create_foreign_key(
        op.f("token_usage_query_id_fkey"), "token_usage", "query", ["query_id"], ["id"]
    )
    op.drop_index(op.f("ix_token_usage_message_id"), table_name="token_usage")
    op.create_index(
        op.f("ix_token_usage_query_id"), "token_usage", ["query_id"], unique=False
    )
    op.drop_column("token_usage", "message_id")
    op.add_column(
        "source",
        sa.Column("answer_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "source", type_="foreignkey")
    op.create_foreign_key(
        op.f("source_answer_id_fkey"), "source", "answer", ["answer_id"], ["id"]
    )
    op.drop_index(op.f("ix_source_message_id"), table_name="source")
    op.create_index(op.f("ix_source_answer_id"), "source", ["answer_id"], unique=False)
    op.drop_column("source", "message_id")
    op.create_table(
        "service_catalog",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('service_catalog_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(length=120), autoincrement=False, nullable=False),
        sa.Column("slug", sa.VARCHAR(length=80), autoincrement=False, nullable=False),
        sa.Column(
            "category", sa.VARCHAR(length=30), autoincrement=False, nullable=False
        ),
        sa.Column(
            "provider", sa.VARCHAR(length=60), autoincrement=False, nullable=False
        ),
        sa.Column(
            "default_config",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="service_catalog_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        op.f("ix_service_catalog_slug"), "service_catalog", ["slug"], unique=True
    )
    op.create_table(
        "answer",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("query_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("answer_text", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "model_used", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "confidence_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["query_id"], ["query.id"], name=op.f("answer_query_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("answer_pkey")),
    )
    op.create_index(op.f("ix_answer_query_id"), "answer", ["query_id"], unique=False)
    op.create_table(
        "user_api_keys",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('user_api_keys_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "user_settings_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("title", sa.VARCHAR(length=512), autoincrement=False, nullable=False),
        sa.Column(
            "encrypted_api_key",
            sa.VARCHAR(length=2048),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name="user_api_keys_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_settings_id"],
            ["user_settings.id"],
            name="user_api_keys_user_settings_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="user_api_keys_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        op.f("ix_user_api_keys_user_settings_id"),
        "user_api_keys",
        ["user_settings_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_api_keys_user_id"), "user_api_keys", ["user_id"], unique=False
    )
    op.create_table(
        "query",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("query_text", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "query_type", sa.VARCHAR(length=20), autoincrement=False, nullable=True
        ),
        sa.Column("parent_query_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_query_id"], ["query.id"], name=op.f("query_parent_query_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["session.id"], name=op.f("query_session_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("query_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("query_pkey")),
    )
    op.create_index(op.f("ix_query_user_id"), "query", ["user_id"], unique=False)
    op.create_index(op.f("ix_query_session_id"), "query", ["session_id"], unique=False)
    op.create_index(
        op.f("ix_query_parent_query_id"), "query", ["parent_query_id"], unique=False
    )
    op.create_table(
        "user_service_credential",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "user_settings_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("service_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("api_key_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "is_default",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["api_key_id"],
            ["user_api_keys.id"],
            name=op.f("user_service_credential_api_key_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["service_catalog.id"],
            name=op.f("user_service_credential_service_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("user_service_credential_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_settings_id"],
            ["user_settings.id"],
            name=op.f("user_service_credential_user_settings_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_service_credential_pkey")),
    )
    op.create_index(
        op.f("ix_user_service_credential_user_settings_id"),
        "user_service_credential",
        ["user_settings_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_service_credential_user_id"),
        "user_service_credential",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_service_credential_service_id"),
        "user_service_credential",
        ["service_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_service_credential_api_key_id"),
        "user_service_credential",
        ["api_key_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_message_user_id"), table_name="message")
    op.drop_index(op.f("ix_message_session_id"), table_name="message")
    op.drop_index(op.f("ix_message_parent_message_id"), table_name="message")
    op.drop_table("message")
    # ### end Alembic commands ###
