"""Added API key table and updated service creds table

Revision ID: 40410cd897af
Revises: 7cc516bf5b60
Create Date: 2025-11-26 12:51:05.260856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40410cd897af'
down_revision: Union[str, None] = '7cc516bf5b60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_service_catalog_slug'), table_name='service_catalog')
    # op.drop_table('service_catalog')
    # op.drop_index(op.f('ix_user_service_credential_service_id'), table_name='user_service_credential')
    # op.drop_index(op.f('ix_user_service_credential_user_id'), table_name='user_service_credential')
    # op.drop_index(op.f('ix_user_service_credential_user_settings_id'), table_name='user_service_credential')
    # op.drop_table('user_service_credential')
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_service_credential',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_settings_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('api_key', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service_catalog.id'], name=op.f('user_service_credential_service_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('user_service_credential_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_settings_id'], ['user_settings.id'], name=op.f('user_service_credential_user_settings_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_service_credential_pkey'))
    )
    op.create_index(op.f('ix_user_service_credential_user_settings_id'), 'user_service_credential', ['user_settings_id'], unique=False)
    op.create_index(op.f('ix_user_service_credential_user_id'), 'user_service_credential', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_service_credential_service_id'), 'user_service_credential', ['service_id'], unique=False)
    op.create_table('service_catalog',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('default_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('service_catalog_pkey'))
    )
    op.create_index(op.f('ix_service_catalog_slug'), 'service_catalog', ['slug'], unique=True)
    # ### end Alembic commands ###
