"""Added session title and like and feedback fields to message

Revision ID: 6e1a23b02603
Revises: 0725003b89aa
Create Date: 2025-11-28 19:59:59.943455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e1a23b02603'
down_revision: Union[str, None] = '0725003b89aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('liked', sa.Boolean(), nullable=True))
    op.add_column('message', sa.Column('feedback', sa.String(length=1024), nullable=True))
    op.add_column('message', sa.Column('stars', sa.Integer(), nullable=True))
    op.add_column('session', sa.Column('title', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'title')
    op.drop_column('message', 'stars')
    op.drop_column('message', 'feedback')
    op.drop_column('message', 'liked')
    # ### end Alembic commands ###
