"""add user role enum

Revision ID: 7cc516bf5b60
Revises: cc7acb66fa00
Create Date: 2025-11-21 00:50:01.146427

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7cc516bf5b60"
down_revision: Union[str, None] = "cc7acb66fa00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the ENUM type first
    user_role_enum = sa.Enum("USER", "ADMIN", name="userrole")
    user_role_enum.create(op.get_bind(), checkfirst=True)

    # Add the column with default value
    op.add_column(
        "user", sa.Column("role", user_role_enum, nullable=False, server_default="USER")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "role")

    # Drop the ENUM type
    user_role_enum = sa.Enum("USER", "ADMIN", name="userrole")
    user_role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
