"""Remove JWT Toekn table

Revision ID: cc7acb66fa00
Revises: 001
Create Date: 2025-11-16 00:04:52.964829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc7acb66fa00'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jwt_token_user_id'), table_name='jwt_token')
    op.drop_table('jwt_token')
    op.add_column('source', sa.Column('source_type', sa.String(length=50), nullable=True))
    op.add_column('user_settings', sa.Column('location', sa.String(length=100), nullable=True))
    op.add_column('user_settings', sa.Column('custom_instructions', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'custom_instructions')
    op.drop_column('user_settings', 'location')
    op.drop_column('source', 'source_type')
    op.create_table('jwt_token',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('device_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('jwt_token_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('jwt_token_pkey')),
    sa.UniqueConstraint('access_token', name=op.f('jwt_token_access_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_jwt_token_user_id'), 'jwt_token', ['user_id'], unique=False)
    # ### end Alembic commands ###
